### ISSUE TITLE
Discord Server / Discussion Place?

### ISSUE THREAD

**Issue by TurkeyKittin** [Erdroy/Stationeers.Addons#1]
This is probably not the right place, and the Trello says this is still TBD, but it would be nice to have some place to discuss work on this. It doesn't seem like there are many mods (if any other than SEGI) that are utilizing this modloader yet.

If there is some other place, let me know!

**Comment by Erdroy** [comment]
Hello!

Yes, it it planned, but it's not something time-consuming, so maybe tomorrow I'll create the server on Discord for our project.
I'll close this issue once it's ready.

And sorry for the late response.

**Comment by Erdroy** [comment]
Discord server is done.
Invite link: https://discord.gg/b6kFrUATdm
