### ISSUE TITLE
If one addon fails to compile this stops working

### ISSUE THREAD

**Issue by silentdeth** [Erdroy/Stationeers.Addons#14]
If an addon fails to compile, this mod loader throws a file not found error for the dll and ceases to function. It should be able to handle such problems more gracefully.

**Comment by Erdroy** [comment]
Sorry for the late response, but this is already fixed for the 0.4 version.
https://github.com/Erdroy/Stationeers.Addons/blob/plugin-compilation-diagnostics/Source/Stationeers.Addons/Modules/Plugins/PluginCompilerModule.cs#L185

But yeah, thanks!
