### ISSUE TITLE
Possible Lockup

### ISSUE THREAD

**Issue by JoelleEmmily** [Erdroy/Stationeers.Addons#17]
Is it possible that there is a mem leak in the mod? I hesitate posting this, as Stationeers has caused this problem as well, but after a long play, and always triggered by something to do with atmospherics, Stationeers will stop exciting scripts. The... GUI for lack of a better word, continues to function, the game still plays, but atmosphere and I think electrical networks cease updating. Attempting to exit or save crashes the game. Again, this may not be your mod as Stationeers with your mod installed but disabled, and without the code injector loaded, does hang link this sometimes.

**Comment by JoelleEmmily** [comment]
[Player.log](https://github.com/Erdroy/Stationeers.Addons/files/10025343/Player.log)
[Player-prev.log](https://github.com/Erdroy/Stationeers.Addons/files/10025345/Player-prev.log)

**Comment by JoelleEmmily** [comment]
I was under the mistaken impression that Elmotrix may have wrote this framework as well as his Atmospheric Realism Overhaul. I believe I may be mistaken. I've captured the crash log and dump, but I'm not sure it'll be relevant to your package. I'll post it here anyway, please ignore if this has nothing to do with your coding.

**Comment by JoelleEmmily** [comment]
[Player.log](https://github.com/Erdroy/Stationeers.Addons/files/10026596/Player.log)
[Player-prev.log](https://github.com/Erdroy/Stationeers.Addons/files/10026597/Player-prev.log)
[dumps.zip](https://github.com/Erdroy/Stationeers.Addons/files/10026601/dumps.zip)

**Comment by Erdroy** [comment]
Well, I'm the creator of Addons but Atmospheric Realism Overhaul is not mine.
As far as I know, no one had similar issue with Addons.
It is really hard to tell, but you could try to remove this Atmospheric Realism Overhaul mod, and see if anything changes.
Maybe the crash is related to the mod doing some changes in multi-threaded code and it produces deadlocks - but that is just my speculation.

Looking just at the dumps, does not tell too much. Same for the logs. It would need a reproduction steps.

**Comment by Erdroy** [comment]
Not really, you can hook up Visual Studio or Jetbrains Rider to the game, with some steps from [here](https://github.com/Erdroy/Stationeers.Addons/blob/master/Docs/DEBUGGING-ADDONS.md), but I don't think so, there will be much for debugging.

IMO the best way at this moment to debug this, is to gradually reduce possible cases - so, Atmospheric Realism Overhaul at first and then Addons itself. 
If removing the Atmo mod will help, I might be able to help, but not sure I'll find enough of free time.
If removing Addons will help, this would be case for me, and I could take a deeper look at.
But if removing both elements won't help, this would be a bug that should be reported to Rocketwerkz.

You can try this, but I suppose it is strictly related to the mod, not Addons or the game.

**Comment by JoelleEmmily** [comment]
Removing the mod... kinda fixes the issue. The issue seems to stem from Stationeers capping the total energy permitted in a network. Base game, or base game with the addon installed, Stationeers ignores any more atmosphere being added into a network once it's reached it's coded maximum.  This still causes issues on save reload, where the network is reset to zero. With the mod installed, the save function... does something that freezes the game, probably because the mod makes the number bigger than the function can handle. I encountered this prior to the reticulation patch, where the energy maximum was e^10 minus one. Rocketwerks has greatly reduced that value, Now it look like 6553500. 100 times hex seems a little odd, but looking into it is at least wasting some of my free time... and keeping the dam over the river of boredom that is life, intact for another little while.

**Comment by JoelleEmmily** [comment]
I was incorrect. The maximum energy value in a network is still e^10, at least on reload. I've been able to pump an atmospheric pipe network to 2-3xe^10 with the game remaining stable, both with and without Elmotex's mod, but with the add-on framework installed. Save functions normally, even saving values larger than e^10, but on load, all contents of over charged networks are set to 0. This limitation existed in the game prior to the reticulation update. I have no idea what caused the consistent crash on save from before... it just kinda went away one of the times I deleted and reinstalled the mod, the framework, and the game... Object errors still abound when playing with pipe networks... but Stationeers has always been touchy regarding network sizes and connecting network together, so is behaving as expected, and does not act abnormally when saved and reloaded. I thought I saw an update pushed by steam, but when I look on Steamdb, it lists no recent patches. It appears this issue was a me problem. Sorry.

**Comment by JoelleEmmily** [comment]
I've tracked the bug down. When an error occurs with an atmospheric network, and the established network is nullified or otherwise corrupted, Stationeers attempts to recover by creating a new network. This new network however, for whatever reason, is not initialized properly, and effects all connected appliances, as well as the math applied to the network. One of the more interesting numeric bugs that results, is that it seems all variables dealing with the network, are reset to 16-bit integers instead of a 32 bit.
