### ISSUE TITLE
Request UniTask.dll reference

### ISSUE THREAD

**Issue by silentdeth** [Erdroy/Stationeers.Addons#18]
I'm requesting a reference to UniTask.dll be added so that mods that use it will compile.

**Comment by Erdroy** [comment]
Sure, I'll do it as soon as possible.

**Comment by Erdroy** [comment]
Sorry for the late fix, but I've added the UniTask to the references and sandbox. Fixed in 26f213a

**Comment by Erdroy** [comment]
It will be available in new release, this should be done in a few days.
