### ISSUE TITLE
Loading Bar in Middle of the Screen

### ISSUE THREAD

**Issue by GBry** [Erdroy/Stationeers.Addons#19]
As titled. Removing Stationeers.Addons fixes this problem, so it is evident. It shows "No State" or something (already removed)

(On Stationeers version 0.2.3719.18087)

**Comment by Erdroy** [comment]
Sorry for the late reply. Could you DM Player.log file to me through Discord?
`C:\Users\%USERNAME%\AppData\LocalLow\Rocketwerkz\rocketstation\Player.log `

Overall, this seems that some mod is failing to load and causing this.

**Comment by GBry** [comment]
I've sent you the file, my handle is HiTechPilot.
