### ISSUE TITLE
Update made ExampleMod error with "GetMissionList" patch

### ISSUE THREAD

**Issue by TurkeyKittin** [Erdroy/Stationeers.Addons#5]
https://github.com/Erdroy/Stationeers.Addons/blob/ccb91540c82fd6b90eedd221a97431b9a618b759/Source/ExampleMod/Scripts/SimplePatch.cs#L9

Need to replace "GetMissionList" with "StartScenario"

**Comment by Erdroy** [comment]
Fixed in 139ad97.
